services:
  - type: worker
    name: abdu_english_bot
    runtime: python
    buildCommand: apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
